### ISSUE TITLE
Implement affine coupling layer

### ISSUE THREAD

**Issue by Lunkers** [Lunkers/DD2412-Project#4]
See paper for details

**Comment by Dayan-Zhanchi** [comment]
List of things still need to be done:

- Test on data, make sure dimensionality is correct through the operations
- Figure out the dimensionality of input data after split, can then add the s values in the class field to buffer instead, so that they will be saved when saving the model parameters
- Fix problem with RGB channel dimension. When the input channel is 3, splitting this in half will not work, since it's an uneven number. Perhaps padding can work? I haven't looked how the authors deal with this.
- Check if t and NN function is used when additive coupling is on.
- Adjust the output dimensionality of last CNN layer accordingly after checking, right now not sure if it's correct output dimension.
- Refactor conv layers into an NN function

**Comment by Dayan-Zhanchi** [comment]
I recall that they used chunks instead of split in the repo, and according to the description of chunks it works even if the dimension is uneven. Possible fix then is to just change split to chunks, but first need to check that all dimensionalities are correct. Perhaps chunks won't help if I've misunderstood something about what should be compatible dimensionalities to begin with for the operations in affine coupling.

![image](https://user-images.githubusercontent.com/16606436/95277715-c1649d80-084e-11eb-904b-3ca51cf63d60.png)

**Comment by Lunkers** [comment]
What i've seen in the official repo is that they use integer division `x // y` to avoid floats in the split
